# Generated by Django 4.2.3 on 2023-08-07 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_bookmark_like_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
