# Generated by Django 4.2.3 on 2023-08-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
